name: CI Entrypoint

on: push

jobs:
  run-tests:
    uses: ./.github/workflows/check_test.yml

  run-installer:
    needs: run-tests
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/test_installer.yml
